---
services:
  db:
    image: postgres
    volumes:
      - ./db_user_local.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_rights
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ../liquibase:/liquibase/changelog
    command: >
      --defaultsFile=/liquibase/changelog/liquibase.local.properties update
    depends_on:
      db:
        condition: service_healthy

  rights:
    build:
      context: ../
      dockerfile: ./local/Dockerfile
    volumes:
      - ../rights.py:/app/rights.py
      - ./config.yaml:/app/config.yaml
    ports:
      - "5080:5080"
    depends_on:
      db:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
