---
# Database address or comma separated list of addresses for client-side DB HA
db_host: localhost

# Database port
db_port: 5432

# Database name
db_db: db_rights

# Database username
db_user: rights_app

# Database user password
db_pass: <PASSWORD>

# Determines if SSL connection will be used
# https://www.postgresql.org/docs/current/libpq-connect.html
# db_ssl_mode: verify-full

# Trusted root CA of database certificate
# db_ssl_root_cert: /etc/ssl/db_root_ca.crt

# Client SSL certificate
# db_ssl_cert: /etc/nginx/xtss-rights/rights.crt

# Client SSL key
# db_ssl_key: /etc/nginx/xtss-rights/rights.key

# Database connection timeout
db_connect_timeout: 5

# If "true" then disable certificate DN check, default value: "false"
allow_all: false

# List of allowed certificate DN's
allowed:
  - OU=XTSS,O=RIA,C=EE

# Log to file instead of stdout if 'log_file' is set and 'logging_config' is not provided
# Note that logrotate is not supported with this logging mode
log_file: /var/log/xtss-rights/rights.log

# Python logging configuration, overrides 'log_file' parameter
# https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig
# NB! Python logging does not support logging from multiple processes to a single file
# https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes
# SocketHandler or StreamHandler are preferred logging classes that should work reliably
# FileHandler or WatchedFileHandler (with logrotate) may work depending on your system
# Rotating file handlers will not work if you have more than one process running
# logging_config:
#   version: 1
#   formatters:
#     standard:
#       format: "%(asctime)s - %(process)d - %(levelname)s: %(message)s"
#   handlers:
#     console:
#       level: INFO
#       formatter: standard
#       class: logging.StreamHandler
#       stream: ext://sys.stderr
#     file:
#       level: INFO
#       formatter: standard
#       class: logging.handlers.WatchedFileHandler
#       filename: /var/log/xtss-rights/rights.log
#   loggers:
#     "":
#       handlers:
#         - console
#         - file
#       level: INFO
#       propagate: true
#     rights:
#       handlers:
#         - console
#         - file
#       level: INFO
#       propagate: false
