---
# Log to file instead of stdout if 'log_file' is set
log_file: /var/log/xtss-rights/rights.log

# Database address or comma separated list of addresses for client-side DB HA
db_host: localhost

# Database port
db_port: 5432

# Database name
db_db: db_rights

# Database username
db_user: rights_app

# Database user password
db_pass: <PASSWORD>

# Determines if SSL connection will be used
# https://www.postgresql.org/docs/current/libpq-connect.html
# db_ssl_mode: verify-full

# Trusted root CA of database certificate
# db_ssl_root_cert: /etc/ssl/db_root_ca.crt

# Client SSL certificate
# db_ssl_cert: /etc/nginx/xtss-rights/rights.crt

# Client SSL key
# db_ssl_key: /etc/nginx/xtss-rights/rights.key

# Database connection timeout
db_connect_timeout: 5

# If "true" then disable certificate DN check, default value: "false"
allow_all: false

# List of allowed certificate DN's
allowed:
  - OU=XTSS,O=RIA,C=EE
